sudo: false
language: csharp
solution: src/Elasticsearch.sln
script: ./build.sh
notifications:
  hipchat:
    rooms:
      secure: Bi1/y587AU+xTXHmHj+Neu1FuxqfIXTjGOespcAyLUvbaHfRCTjYU7mEFqelZHP/tO0TQQ1uqxmnPvIsJ0yeO827Sq0pi21yS9qih6IBt1gEpX4X4/8LfkzIPSFN0OFFpkLn+3u1C8V3jPAZ5fspKAFe3UZ4fePmHx2oRaTGwC8=
